import { MapPinned, PackageCheck, Clock8, ShieldCheck, Feather } from "lucide-react";

export const categories = [
  {
    name: "Home Decor",
    count: "6 products",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Kitchen",
    count: "3 products",
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Bottles",
    count: "7 products",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Fans",
    count: "6 products",
    image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Lunch Box",
    count: "3 products",
    image: "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Storage",
    count: "6 products",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Textiles",
    count: "1 product",
    image: "https://images.unsplash.com/photo-1604578762246-41134e37f9cc?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Gifting",
    count: "2 products",
    image: "https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Sale",
    count: "22 products",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=600&q=80",
  },
];

export const products = [
  {
    name: "Printed Temperature Bottle",
    slug: "printed-temperature-bottle-imported",
    price: "Rs. 675",
    oldPrice: "Rs. 844",
    salePrice: 675,
    originalPrice: 844,
    sku: "JA-CC3078",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Smart Drinkware | Temperature Display",
    description: "Printed temperature bottle with LED display. Smart thermos cup that shows the real-time temperature of your drink.",
    categories: ["Bottles"],
    rating: "4.8",
    reviews: "14",
    inStock: true,
    image: "/images/products/temp-bottle.jpg",
  },
  {
    name: "203B Portable Handy Fan",
    slug: "203b-portable-handy-fan-imported",
    price: "Rs. 540",
    oldPrice: "Rs. 675",
    salePrice: 540,
    originalPrice: 675,
    sku: "JA-CC3137",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Personal Cooling | Handy Fan",
    description: "Compact portable handy fan for quick cooling on the go. USB rechargeable with strong airflow.",
    categories: ["Fans"],
    rating: "4.7",
    reviews: "22",
    inStock: true,
    image: "/images/products/handy-fan.jpg",
  },
  {
    name: "Adjustable Bladeless Neck Fan",
    slug: "adjustable-bladeless-neck-fan-imported",
    price: "Rs. 800",
    oldPrice: "Rs. 1000",
    salePrice: 800,
    originalPrice: 1000,
    sku: "JA-CC2709",
    badge: "Best Seller",
    badgeClass: "badge-hot",
    detail: "Personal Cooling | Hands-Free",
    description: "The ultimate hands-free cooling solution. This bladeless neck fan features 360° airflow, ultra-quiet operation, and a lightweight ergonomic design. Perfect for commuting, workouts, and outdoor activities.",
    categories: ["Fans", "Daily Carry"],
    rating: "4.9",
    reviews: "156",
    inStock: true,
    image: "/images/products/neck-fan.png",
    gallery: [
      "/images/products/neck-fan.png",
      "/images/hero/neck-fan-multi.png",
      "/images/neck-fan-hero.jpg"
    ],
    highlights: [
      "360° Surround Airflow for instant cooling",
      "Bladeless Design - Safe for long hair",
      "3 Speed Settings: Low, Medium, High",
      "USB Rechargeable: Up to 8 hours battery life",
      "Ergonomic & Lightweight: Only 250g"
    ],
    specifications: {
      "Material": "Skin-friendly ABS + Silicone",
      "Battery": "4000mAh Lithium Ion",
      "Charging": "Type-C (Fast Charging)",
      "Runtime": "4-16 Hours depending on speed",
      "Noise Level": "< 25dB (Ultra Quiet)"
    },
    colors: [
      { name: "Forest Green", hex: "#2D4B3F", image: "/images/hero/neck-fan-multi.png" },
      { name: "Blush Pink", hex: "#E8C2C2", image: "/images/hero/neck-fan-multi.png" },
      { name: "Arctic White", hex: "#F5F5F5", image: "/images/hero/neck-fan-multi.png" }
    ]
  },
  {
    name: "Mini Portable Wall Mounted AC",
    slug: "mini-portable-wall-mounted-ac-imported",
    price: "Rs. 3475",
    oldPrice: "Rs. 4344",
    salePrice: 3475,
    originalPrice: 4344,
    sku: "JA-CC3220",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Home Cooling | Heating & Cooling",
    description: "Compact wall-mounted AC unit for personal cooling and heating. Imported quality with remote control.",
    categories: ["Fans", "Home Decor"],
    rating: "4.7",
    reviews: "8",
    inStock: true,
    image: "/images/products/portable-ac.jpg",
    gallery: [
      "/images/products/portable-ac.jpg",
      "/images/products/portable-ac-feature-1.jpg",
      "/images/products/portable-ac-feature-2.jpg"
    ],
    highlights: [
      "Dual Function: Cooling & Heating",
      "Remote Control for easy operation",
      "Compact Wall-Mounted Design",
      "Energy Efficient Technology",
      "Quiet Operation (< 35dB)"
    ],
    specifications: {
      "Power": "2000W",
      "Voltage": "220V",
      "Coverage": "Up to 150 sq. ft.",
      "Modes": "Cool / Heat / Fan",
      "Timer": "Up to 12 Hours"
    }
  },
  {
    name: "Mist Double Headed LED Fan",
    slug: "mist-double-headed-led-fan-imported",
    price: "Rs. 2250",
    oldPrice: "Rs. 2813",
    salePrice: 2250,
    originalPrice: 2813,
    sku: "JA-CC3221",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Personal Cooling | Mist Fan",
    description: "Mist double headed LED fan with remote or battery operation. Circulates fresh air with 120 degree rotary mist.",
    categories: ["Fans"],
    rating: "4.8",
    reviews: "12",
    inStock: true,
    image: "/images/products/mist-fan.jpg",
  },
  {
    name: "Hamburger Kids Lunch Box",
    slug: "hamburger-kids-lunch-box",
    price: "Rs. 285",
    oldPrice: "Rs. 356",
    salePrice: 285,
    originalPrice: 356,
    sku: "JA-CC2622",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Lunch Box | Kids Essentials",
    description: "Fun hamburger shaped lunch box with multi-compartments and secure clip locks. Food grade material.",
    categories: ["Lunch Box", "Storage"],
    rating: "4.9",
    reviews: "25",
    inStock: true,
    image: "/images/products/lunch-box.jpg",
    gallery: [
      "/images/products/lunch-box-feature-3.jpg",
      "/images/products/lunch-box.jpg",
      "/images/products/lunch-box-feature-1.jpg",
      "/images/products/lunch-box-feature-2.jpg"
    ]
  },
  {
    name: "AA-128 Fancy Glass Sipper Tumbler",
    slug: "aa-128-fancy-glass-sipper-tumbler-imported",
    price: "Rs. 335",
    oldPrice: "Rs. 419",
    moq: 2,
    discountPercent: "20% off",
    salePrice: 335,
    originalPrice: 419,
    sku: "JA-CC3223",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Drinkware | Glass Sipper",
    description: "Fancy cartoon bear glass sipper tumbler. Sealed and leak-proof with various options available.",
    categories: ["Bottles", "Kitchen"],
    rating: "4.6",
    reviews: "18",
    inStock: true,
    image: "/images/products/glass-sipper.jpg",
    material: "BPA Free Food Grade Glass",
    capacity: "500ml",
    gallery: [
      "/images/products/glass-sipper.jpg",
      "/images/products/glass-sipper-feature-1.jpg",
      "/images/products/glass-sipper-feature-2.jpg"
    ]
  },
  {
    name: "B-111 1200ml Bluetooth Speaker Tumbler",
    slug: "b-111-1200ml-bluetooth-speaker-tumbler-imported",
    price: "Rs. 3950",
    oldPrice: "Rs. 4938",
    salePrice: 3950,
    originalPrice: 4938,
    sku: "JA-CC2683",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Drinkware | Bluetooth Speaker",
    description: "Stainless steel tumbler with built-in Bluetooth speaker. Keeps drinks hot or cold with 1200ml capacity.",
    categories: ["Bottles", "Storage"],
    rating: "4.8",
    reviews: "30",
    inStock: true,
    image: "/images/products/speaker-tumbler.jpg",
    material: "Premium Stainless Steel",
    capacity: "1200ml / Extra Large",
    gallery: [
      "/images/products/speaker-tumbler.jpg",
      "/images/products/speaker-tumbler-2.jpg"
    ],
    highlights: [
      "Detachable Bluetooth Speaker base",
      "IPX6 Water Resistant Speaker",
      "Double-walled Vacuum Insulation",
      "12 Hours Hot / 24 Hours Cold",
      "Large 1200ml Capacity"
    ],
    specifications: {
      "Material": "18/8 Stainless Steel",
      "Bluetooth": "Version 5.0",
      "Battery": "1000mAh (6 Hours Playtime)",
      "Charging": "Micro-USB",
      "Lid Type": "Leak-proof Slider"
    }
  },
  {
    name: "Hammered Copper Bottle",
    slug: "hammered-copper-bottle",
    price: "Rs. 4495",
    oldPrice: "Rs. 5619",
    salePrice: 4495,
    originalPrice: 5619,
    badge: "New",
    detail: "Insulated daily carry",
    categories: ["Bottles", "Daily Carry"],
    rating: "4.8",
    reviews: "1,248",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Acacia Serving Bowl",
    slug: "acacia-serving-bowl",
    price: "Rs. 7250",
    oldPrice: "Rs. 9063",
    salePrice: 7250,
    originalPrice: 9063,
    badge: "Best Seller",
    badgeClass: "badge-dark",
    detail: "Hand-finished wood",
    categories: ["Kitchen", "Home Decor"],
    rating: "4.7",
    reviews: "864",
    image: "https://images.unsplash.com/photo-1601985705806-5b9a71f6004f?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Stoneware Planter Set",
    slug: "stoneware-planter-set",
    price: "Rs. 5495",
    oldPrice: "Rs. 6869",
    salePrice: 5495,
    originalPrice: 6869,
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Set of two planters",
    categories: ["Home Decor", "Storage"],
    rating: "4.6",
    reviews: "519",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Insulated Lunch Carrier",
    slug: "insulated-lunch-carrier",
    price: "Rs. 3995",
    oldPrice: "Rs. 4994",
    salePrice: 3995,
    originalPrice: 4994,
    detail: "Compact workday storage",
    categories: ["Lunch Box", "Storage"],
    rating: "4.5",
    reviews: "410",
    image: "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Minimal Desk Organizer",
    slug: "minimal-desk-organizer",
    price: "Rs. 3250",
    oldPrice: "Rs. 4063",
    salePrice: 3250,
    originalPrice: 4063,
    badge: "Fresh Drop",
    detail: "Calm desk essentials",
    categories: ["Home Decor", "Storage"],
    rating: "4.4",
    reviews: "283",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Ribbed Glass Tumbler",
    slug: "ribbed-glass-tumbler",
    price: "Rs. 1995",
    oldPrice: "Rs. 2494",
    salePrice: 1995,
    originalPrice: 2494,
    detail: "Everyday glassware",
    categories: ["Kitchen", "Bottles"],
    rating: "4.6",
    reviews: "932",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Cotton Table Runner",
    slug: "cotton-table-runner",
    price: "Rs. 3745",
    oldPrice: "Rs. 4681",
    salePrice: 3745,
    originalPrice: 4681,
    detail: "Soft woven cotton",
    categories: ["Textiles", "Home Decor"],
    rating: "4.3",
    reviews: "190",
    image: "https://images.unsplash.com/photo-1604578762246-41134e37f9cc?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Matte Ceramic Vase",
    slug: "matte-ceramic-vase",
    price: "Rs. 6250",
    oldPrice: "Rs. 7813",
    salePrice: 6250,
    originalPrice: 7813,
    badge: "Limited",
    badgeClass: "badge-dark",
    detail: "Shelf-ready accent",
    categories: ["Home Decor", "Gifting"],
    rating: "4.7",
    reviews: "351",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "V8 OTG Fan",
    slug: "v8-otg-fan",
    price: "Rs. 80",
    oldPrice: "Rs. 100",
    salePrice: 80,
    originalPrice: 100,
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "OTG Fan | Mobile Fan",
    description: "Compact OTG fan for quick personal cooling while using compatible mobile devices.",
    categories: ["Fans"],
    rating: "4.8",
    reviews: "0",
    stock: 100,
    active: true,
    inStock: true,
    photoCount: "2 photos",
    image: "/images/products/new-products/v8-otg-fan.svg",
  },
  {
    name: "RL-7064 Table Fan",
    slug: "rl-7064-table-fan",
    price: "Rs. 2475",
    oldPrice: "Rs. 3094",
    salePrice: 2475,
    originalPrice: 3094,
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Table Fan | Portable Fan",
    description: "Portable table fan for desk, bedside, and small-room personal cooling.",
    categories: ["Fans"],
    rating: "4.8",
    reviews: "0",
    stock: 100,
    active: true,
    inStock: true,
    photoCount: "2 photos",
    image: "/images/products/new-products/rl-7064-table-fan.svg",
  },
  {
    name: "B-84 Unicorn Printed Temperature Bottle",
    slug: "b-84-unicorn-printed-temperature-bottle-imported",
    price: "Rs. 660",
    oldPrice: "Rs. 825",
    salePrice: 660,
    originalPrice: 825,
    badge: "20% Off",
    badgeClass: "badge-discount",
    stockBadge: "Out of Stock",
    detail: "Temperature Bottle | Kids Bottle",
    description: "Imported unicorn printed temperature bottle for kids and daily carry.",
    categories: ["Bottles"],
    rating: "4.8",
    reviews: "0",
    stock: 0,
    active: true,
    inStock: false,
    photoCount: "3 photos",
    image: "/images/products/new-products/b-84-unicorn-printed-temperature-bottle.svg",
  },
  {
    name: "Transparent Leak Proof Lunch Box",
    slug: "transparent-leak-proof-lunch-box",
    price: "Rs. 275",
    oldPrice: "Rs. 344",
    salePrice: 275,
    originalPrice: 344,
    badge: "20% Off",
    badgeClass: "badge-discount",
    stockBadge: "Out of Stock",
    detail: "lunch box | Leak Proof",
    description: "Transparent leak proof lunch box for compact meal storage and daily use.",
    categories: ["Lunch Box", "Storage"],
    rating: "4.8",
    reviews: "0",
    stock: 0,
    active: true,
    inStock: false,
    image: "/images/products/new-products/transparent-leak-proof-lunch-box.svg",
  },
  {
    name: "B-07 Premium Nice Glass Bottle",
    slug: "b-07-premium-nice-glass-bottle",
    price: "Rs. 260",
    oldPrice: "Rs. 325",
    salePrice: 260,
    originalPrice: 325,
    badge: "20% Off",
    badgeClass: "badge-discount",
    stockBadge: "Out of Stock",
    detail: "water bottles | Drinkware",
    description: "Premium glass bottle with a clean look for gifting, carry, and everyday drinkware.",
    categories: ["Bottles", "Gifting"],
    rating: "4.8",
    reviews: "0",
    stock: 0,
    active: true,
    inStock: false,
    photoCount: "5 photos",
    image: "/images/products/new-products/b-07-premium-nice-glass-bottle.svg",
  },
  {
    name: "After Hours Eau De Parfum",
    slug: "after-hours-perfume",
    price: "Rs. 6450",
    oldPrice: "Rs. 8063",
    salePrice: 6450,
    originalPrice: 8063,
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "Premium Fragrance | Long Lasting",
    description: "A sophisticated blend of deep woody notes and fresh citrus, designed for the modern evening. Long-lasting sillage.",
    categories: ["Gifting", "Daily Carry"],
    rating: "4.9",
    reviews: "42",
    inStock: true,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Mini 300ML Stainless Steel Bottle",
    slug: "mini-stainless-steel-bottle-imported",
    price: "Rs. 1060",
    oldPrice: "Rs. 1325",
    salePrice: 1060,
    originalPrice: 1325,
    sku: "JA-CC2762",
    badge: "20% Off",
    badgeClass: "badge-discount",
    detail: "304 Stainless Steel | 7 Color Stock",
    description: "Compact and durable 300ML stainless steel thermos bottle. 304 food-grade material with vacuum insulation to keep drinks hot or cold.",
    categories: ["Bottles", "Daily Carry"],
    rating: "4.9",
    reviews: "15",
    inStock: true,
    image: "/images/products/mini-steel-bottle.jpg",
    material: "304 Food-Grade Stainless Steel",
    capacity: "300ml / Compact",
    gallery: [
      "/images/products/mini-steel-bottle.jpg",
      "/images/products/mini-steel-bottle-2.jpg",
      "/images/products/mini-steel-bottle-3.jpg"
    ],
    highlights: [
      "Ultra-compact pocket friendly size",
      "304 Food-Grade Stainless Steel",
      "Leak-proof screw cap with seal",
      "Matte Finish - Scratch Resistant",
      "Keeps drinks at temp for 6+ hours"
    ],
    specifications: {
      "Height": "15cm",
      "Diameter": "6cm",
      "Weight": "180g",
      "Insulation": "Double Wall Vacuum",
      "Finish": "Powder Coated"
    }
  },
];

export const heroSlides = [
  {
    eyebrow: "Summer Essentials",
    title: "Super cool Portable air conditioner",
    copy: "",
    cta: "Shop Now",
    image: "/images/hero/neck-fan-multi.png",
    link: "/product/adjustable-bladeless-neck-fan-imported",
    price: "Rs. 800",
    oldPrice: "Rs. 1000",
  },
  {
    eyebrow: "Daily Essential",
    title: "304 Stainless Steel Thermos",
    copy: "",
    cta: "Shop Now",
    image: "/images/hero/thermos-bottle.png",
    link: "/product/304-stainless-steel-thermos-bottle",
    price: "Rs. 450",
    oldPrice: "Rs. 600",
  },
];

export const peopleChoiceVideos = [
  {
    title: "Adjustable Bladeless Neck Fan",
    price: "Rs. 800",
    oldPrice: "Rs. 1000",
    image: "/images/products/neck-fan.png",
    video: "/videos/adjustable-bladeless-neck-fan.mp4",
    thumb: "/images/products/neck-fan.png",
    slug: "adjustable-bladeless-neck-fan-imported",
  },
  {
    title: "Mini Portable Wall Mounted AC",
    price: "Rs. 3475",
    oldPrice: "Rs. 4344",
    image: "/images/products/portable-ac.jpg",
    video: "/videos/mini-portable-wall-mounted-ac.mp4",
    thumb: "/images/products/portable-ac.jpg",
    slug: "mini-portable-wall-mounted-ac-imported",
  },
  {
    title: "Hamburger Kids Lunch Box",
    price: "Rs. 285",
    oldPrice: "Rs. 356",
    image: "/images/products/lunch-box.jpg",
    video: "https://assets.mixkit.co/videos/preview/mixkit-hamburger-and-fries-placed-on-a-table-4148-large.mp4",
    thumb: "/images/products/lunch-box.jpg",
    slug: "hamburger-kids-lunch-box",
  },
  {
    title: "V8 OTG Fan | Mobile Fan",
    price: "Rs. 80",
    oldPrice: "Rs. 100",
    image: "/images/products/new-products/v8-otg-fan.svg",
    video: "https://pin.it/7kYEkablQ",
    thumb: "/images/products/new-products/v8-otg-fan.svg",
    slug: "v8-otg-fan",
  },
];

export const pubestoTrustFeatures = [
  { label: "Quality-checked products", mark: "QC" },
  { label: "Made for Indian homes", Icon: MapPinned },
  { label: "Secure packaging", Icon: PackageCheck },
  { label: "Fast dispatch on most orders", Icon: Clock8 },
  { label: "Easy returns and support", Icon: ShieldCheck },
  { label: "Useful daily essentials", Icon: Feather },
  { label: "Value pricing on trusted picks", mark: "Rs" },
];

export const socialGalleryItems = [
  {
    title: "Carry it clean",
    caption: "Bottles for desk, school, and daily errands.",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=86",
  },
  {
    title: "Pack the day",
    caption: "Lunch storage that keeps workdays simple.",
    image: "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=900&q=86",
  },
  {
    title: "Cool corners",
    caption: "Compact fans and comfort picks for home.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=86",
  },
  {
    title: "Everyday edits",
    caption: "Useful finds styled for Indian homes.",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=86",
  },
];

export const fragranceProducts = [
  {
    name: "Silken Ember",
    price: "",
    numericPrice: 210,
    detail: "Eau de Parfum",
    notes: ["Sandalwood", "White Pepper", "Iris"],
    family: "Woody",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Veridant Vault",
    price: "",
    numericPrice: 185,
    detail: "Eau de Parfum",
    notes: ["Vetiver", "Oakmoss", "Bergamot"],
    family: "Citrus",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Oud Architecture",
    price: "",
    numericPrice: 320,
    detail: "Eau de Parfum",
    notes: ["Agarwood", "Saffron", "Rose"],
    family: "Spicy",
    image: "https://images.unsplash.com/photo-1585232351009-aa87416fca90?auto=format&fit=crop&w=800&q=85",
  },
  {
    name: "Concrete Petal",
    price: "",
    numericPrice: 195,
    detail: "Eau de Parfum",
    notes: ["Jasmine", "Patchouli", "Musk"],
    family: "Floral",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=85",
  },
];


